apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transform-${PROJECT}-${GH_ORGANIZATION}-${GH_REPOSITORY}-${TRANSFORM_METRIC}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transform
        project: ${PROJECT}
        gh-organization: ${GH_ORGANIZATION}
        gh-repository: ${GH_REPOSITORY}
        transform-plugin: ${TRANSFORM_PLUGIN}
        transform-metric: ${TRANSFORM_METRIC}
    spec:
      containers:
      - name: transform
        args:
        - --repository=${GH_ORGANIZATION}/${GH_REPOSITORY}
        - --stderrthreshold=0
        - --host=sqlproxy
        - --influx-host=http://influxdb-${PROJECT}:8086
        - --influx-password=$(INFLUXDB_ROOT_PWD)
        - --name=${TRANSFORM_METRIC}
        - ${TRANSFORM_PLUGIN}
        # plugin args should be appended here.
        image: gcr.io/google-containers/github-transform:v20170310-101209
        resources:
          requests:
            cpu: 0m
        env:
        - name: INFLUXDB_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: influxdb-${PROJECT}
              key: rootpassword
