projects:
  kubernetes:
    repositories:
      kubernetes/kubernetes: &kubernetes-transform
        first-comment:
          plugin: "first_comment"
          args:
            - --bots=k8s-merge-robot,k8s-reviewable,k8s-ci-robot
        merge:
          plugin: "event_count"
          args:
            - --event=merged
        lgtm:
          plugin: "event_count"
          args:
            - --event=labeled:lgtm
        approved:
          plugin: "event_count"
          args:
            - --event=labeled:approved
      kubernetes/test-infra: *kubernetes-transform
      kubernetes/contrib: *kubernetes-transform
    nginx:
      public-ip: "104.197.200.129"
    grafana:
      google-analytics-uaid: "UA-82843984-3"
    prometheus:
      prometheus-config.yml: |
        global:
          scrape_interval: 1m
        scrape_configs:
          - job_name: kubernetes-submit-queue
            metrics_path: /prometheus
            static_configs:
              - targets:
                  - submit-queue.k8s.io
  istio:
    repositories:
      istio/api:
      istio/auth:
      istio/istio:
      istio/manager:
      istio/mixer:
      istio/proxy:
    nginx:
      public-ip:
    grafana:
      google-analytics-uaid: ""
  tensorflow:
    repositories:
      tensorflow/tensorflow:
    grafana:
      google-analytics-uaid: ""
    nginx:
      public-ip:
  beam:
    repositories:
      apache/beam:
      apache/beam-site:
    grafana:
      google-analytics-uaid: ""
