# The following metrics configuration will work with the default dashboard template.
# merge:
#   plugin: count
#   args:
#     - --no-issues
#     - --event=merged
# contributions:
#   plugin: count
#   args:
#     - --ignore-authors=k8s-merge-robot,k8s-reviewable,k8s-ci-robot
#     - --no-issues
#     - --event=opened
#     - --comments=.*
#     - --log-author
# open:
#   plugin: count
#   args:
#     - --no-issues
#     - --state=opened,!merged
#     - --percentiles=50
projects:
  kubernetes:
    repositories:
      kubernetes/kubernetes: &kubernetes-transform
        merge:
          plugin: count
          args:
            - --no-issues
            - --event=merged
        contributions:
          plugin: count
          args:
            - --ignore-authors=k8s-merge-robot,k8s-reviewable,k8s-ci-robot
            - --no-issues
            - --event=opened
            - --comments=.*
            - --log-author
        open:
          plugin: count
          args:
            - --no-issues
            - --state=opened,!merged
            - --percentiles=50
        needs-rebase:
          plugin: count
          args:
            - --no-issues
            - --percentiles=50
            - --state=opened,labeled:needs-rebase
        lgtmed:
          plugin: count
          args:
            - --no-issues
            - --percentiles=50
            - --state=opened,!labeled:needs-rebase,labeled:lgtm
        approved:
          plugin: count
          args:
            - --no-issues
            - --percentiles=50
            - --state=opened,!labeled:needs-rebase,labeled:approved
        lgtmer:
          plugin: count
          args:
            - --no-issues
            - --ignore-authors=k8s-merge-robot
            - --event=labeled:lgtm
            - --comments=(?m)^/lgtm$
            - --log-author
        approver:
          plugin: count
          args:
            - --no-issues
            - --ignore-authors=k8s-merge-robot
            - --event=labeled:approved
            - --comments=(?m)^/approve$
            - --log-author
        testthis:
          plugin: count
          args:
            - --no-issues
            - --ignore-authors=k8s-merge-robot,k8s-ci-robot
            - --comments=(?m)^@k8s-bot.*test this
      kubernetes/test-infra: *kubernetes-transform
      kubernetes/contrib: *kubernetes-transform
    nginx:
      public-ip: "104.197.200.129"
    grafana:
      google-analytics-uaid: "UA-82843984-3"
    prometheus:
      prometheus-config.yml: |
        global:
          scrape_interval: 1m
        scrape_configs:
          - job_name: kubernetes-submit-queue
            metrics_path: /prometheus
            static_configs:
              - targets:
                  - submit-queue.k8s.io
  istio:
    repositories:
      istio/api: &transform-istio
        merge:
          plugin: count
          args:
            - --no-issues
            - --event=merged
        contributions:
          plugin: count
          args:
            - --no-issues
            - --event=opened
            - --comments=.*
            - --log-author
        open:
          plugin: count
          args:
            - --no-issues
            - --state=opened,!merged
            - --percentiles=50
      istio/auth: *transform-istio
      istio/istio: *transform-istio
      istio/manager: *transform-istio
      istio/mixer: *transform-istio
      istio/proxy: *transform-istio
    nginx:
      public-ip:
    grafana:
      google-analytics-uaid: ""
  tensorflow:
    repositories:
      tensorflow/tensorflow:
        merge:
          plugin: count
          args:
            - --no-issues
            - --event=merged
        contributions:
          plugin: count
          args:
            - --no-issues
            - --event=opened
            - --comments=.*
            - --log-author
        open:
          plugin: count
          args:
            - --no-issues
            - --state=opened,!merged
            - --percentiles=50
    grafana:
      google-analytics-uaid: ""
    nginx:
      public-ip:
  beam:
    repositories:
      apache/beam: &transform-beam
        merge:
          plugin: count
          args:
            - --no-issues
            - --event=merged
        contributions:
          plugin: count
          args:
            - --no-issues
            - --event=opened
            - --comments=.*
            - --log-author
        open:
          plugin: count
          args:
            - --no-issues
            - --state=opened,!merged
            - --percentiles=50
      apache/beam-site: *transform-beam
    grafana:
      google-analytics-uaid: ""
